/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface AucentiveHubInterface extends ethers.utils.Interface {
  functions: {
    "USDC()": FunctionFragment;
    "createService(bytes32,uint256,uint64)": FunctionFragment;
    "execute(bytes32,string,string,bytes)": FunctionFragment;
    "executeWithToken(bytes32,string,string,bytes,string,uint256)": FunctionFragment;
    "gasService()": FunctionFragment;
    "gateway()": FunctionFragment;
    "getSettledData(bytes32,string)": FunctionFragment;
    "modifyOpimisticOracle(address)": FunctionFragment;
    "modifyServiceStatus(bytes32,uint8,address,address)": FunctionFragment;
    "oo()": FunctionFragment;
    "owner()": FunctionFragment;
    "payForService(bytes32,uint256)": FunctionFragment;
    "requestData(bytes32,string)": FunctionFragment;
    "requestTimes(bytes32)": FunctionFragment;
    "settleRequest(bytes32,string)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "withdrawBalanceViaAdmin(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "USDC", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "createService",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "execute",
    values: [BytesLike, string, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeWithToken",
    values: [BytesLike, string, string, BytesLike, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "gasService",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "gateway", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getSettledData",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "modifyOpimisticOracle",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "modifyServiceStatus",
    values: [BytesLike, BigNumberish, string, string]
  ): string;
  encodeFunctionData(functionFragment: "oo", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payForService",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestData",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "requestTimes",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "settleRequest",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawBalanceViaAdmin",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "USDC", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createService",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeWithToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gasService", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gateway", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSettledData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "modifyOpimisticOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "modifyServiceStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "oo", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "payForService",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestTimes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawBalanceViaAdmin",
    data: BytesLike
  ): Result;

  events: {
    "ServiceCancelled(bytes32)": EventFragment;
    "ServiceCompleted(bytes32)": EventFragment;
    "ServicePaid(bytes32,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ServiceCancelled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ServiceCompleted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ServicePaid"): EventFragment;
}

export type ServiceCancelledEvent = TypedEvent<
  [string] & { serviceId: string }
>;

export type ServiceCompletedEvent = TypedEvent<
  [string] & { serviceId: string }
>;

export type ServicePaidEvent = TypedEvent<
  [string, BigNumber] & { serviceId: string; payAmount: BigNumber }
>;

export class AucentiveHub extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: AucentiveHubInterface;

  functions: {
    USDC(overrides?: CallOverrides): Promise<[string]>;

    createService(
      serviceId: BytesLike,
      minAmount: BigNumberish,
      duration: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    execute(
      commandId: BytesLike,
      sourceChain: string,
      sourceAddress: string,
      payload: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    executeWithToken(
      commandId: BytesLike,
      sourceChain: string,
      sourceAddress: string,
      payload: BytesLike,
      tokenSymbol: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    gasService(overrides?: CallOverrides): Promise<[string]>;

    gateway(overrides?: CallOverrides): Promise<[string]>;

    getSettledData(
      identifier: BytesLike,
      ancillaryString: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    modifyOpimisticOracle(
      _oo: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    modifyServiceStatus(
      serviceId: BytesLike,
      status: BigNumberish,
      serviceSender: string,
      serviceRecipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    oo(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    payForService(
      serviceId: BytesLike,
      payAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    requestData(
      identifier: BytesLike,
      ancillaryString: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    requestTimes(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    settleRequest(
      identifier: BytesLike,
      ancillaryString: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdrawBalanceViaAdmin(
      recipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  USDC(overrides?: CallOverrides): Promise<string>;

  createService(
    serviceId: BytesLike,
    minAmount: BigNumberish,
    duration: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  execute(
    commandId: BytesLike,
    sourceChain: string,
    sourceAddress: string,
    payload: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  executeWithToken(
    commandId: BytesLike,
    sourceChain: string,
    sourceAddress: string,
    payload: BytesLike,
    tokenSymbol: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  gasService(overrides?: CallOverrides): Promise<string>;

  gateway(overrides?: CallOverrides): Promise<string>;

  getSettledData(
    identifier: BytesLike,
    ancillaryString: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  modifyOpimisticOracle(
    _oo: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  modifyServiceStatus(
    serviceId: BytesLike,
    status: BigNumberish,
    serviceSender: string,
    serviceRecipient: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  oo(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  payForService(
    serviceId: BytesLike,
    payAmount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  requestData(
    identifier: BytesLike,
    ancillaryString: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  requestTimes(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

  settleRequest(
    identifier: BytesLike,
    ancillaryString: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdrawBalanceViaAdmin(
    recipient: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    USDC(overrides?: CallOverrides): Promise<string>;

    createService(
      serviceId: BytesLike,
      minAmount: BigNumberish,
      duration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    execute(
      commandId: BytesLike,
      sourceChain: string,
      sourceAddress: string,
      payload: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    executeWithToken(
      commandId: BytesLike,
      sourceChain: string,
      sourceAddress: string,
      payload: BytesLike,
      tokenSymbol: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    gasService(overrides?: CallOverrides): Promise<string>;

    gateway(overrides?: CallOverrides): Promise<string>;

    getSettledData(
      identifier: BytesLike,
      ancillaryString: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    modifyOpimisticOracle(
      _oo: string,
      overrides?: CallOverrides
    ): Promise<void>;

    modifyServiceStatus(
      serviceId: BytesLike,
      status: BigNumberish,
      serviceSender: string,
      serviceRecipient: string,
      overrides?: CallOverrides
    ): Promise<void>;

    oo(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    payForService(
      serviceId: BytesLike,
      payAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    requestData(
      identifier: BytesLike,
      ancillaryString: string,
      overrides?: CallOverrides
    ): Promise<void>;

    requestTimes(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    settleRequest(
      identifier: BytesLike,
      ancillaryString: string,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawBalanceViaAdmin(
      recipient: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "ServiceCancelled(bytes32)"(
      serviceId?: null
    ): TypedEventFilter<[string], { serviceId: string }>;

    ServiceCancelled(
      serviceId?: null
    ): TypedEventFilter<[string], { serviceId: string }>;

    "ServiceCompleted(bytes32)"(
      serviceId?: null
    ): TypedEventFilter<[string], { serviceId: string }>;

    ServiceCompleted(
      serviceId?: null
    ): TypedEventFilter<[string], { serviceId: string }>;

    "ServicePaid(bytes32,uint256)"(
      serviceId?: null,
      payAmount?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { serviceId: string; payAmount: BigNumber }
    >;

    ServicePaid(
      serviceId?: null,
      payAmount?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { serviceId: string; payAmount: BigNumber }
    >;
  };

  estimateGas: {
    USDC(overrides?: CallOverrides): Promise<BigNumber>;

    createService(
      serviceId: BytesLike,
      minAmount: BigNumberish,
      duration: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    execute(
      commandId: BytesLike,
      sourceChain: string,
      sourceAddress: string,
      payload: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    executeWithToken(
      commandId: BytesLike,
      sourceChain: string,
      sourceAddress: string,
      payload: BytesLike,
      tokenSymbol: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    gasService(overrides?: CallOverrides): Promise<BigNumber>;

    gateway(overrides?: CallOverrides): Promise<BigNumber>;

    getSettledData(
      identifier: BytesLike,
      ancillaryString: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    modifyOpimisticOracle(
      _oo: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    modifyServiceStatus(
      serviceId: BytesLike,
      status: BigNumberish,
      serviceSender: string,
      serviceRecipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    oo(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    payForService(
      serviceId: BytesLike,
      payAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    requestData(
      identifier: BytesLike,
      ancillaryString: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    requestTimes(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    settleRequest(
      identifier: BytesLike,
      ancillaryString: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdrawBalanceViaAdmin(
      recipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    USDC(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    createService(
      serviceId: BytesLike,
      minAmount: BigNumberish,
      duration: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    execute(
      commandId: BytesLike,
      sourceChain: string,
      sourceAddress: string,
      payload: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    executeWithToken(
      commandId: BytesLike,
      sourceChain: string,
      sourceAddress: string,
      payload: BytesLike,
      tokenSymbol: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    gasService(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    gateway(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getSettledData(
      identifier: BytesLike,
      ancillaryString: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    modifyOpimisticOracle(
      _oo: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    modifyServiceStatus(
      serviceId: BytesLike,
      status: BigNumberish,
      serviceSender: string,
      serviceRecipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    oo(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    payForService(
      serviceId: BytesLike,
      payAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    requestData(
      identifier: BytesLike,
      ancillaryString: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    requestTimes(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    settleRequest(
      identifier: BytesLike,
      ancillaryString: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdrawBalanceViaAdmin(
      recipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
